---
version: "2.1"
services:
  # -- TVH IPTV CONFIG --
  tvh_iptv:
    image: josh5/tvh-iptv:latest
    container_name: tvh_iptv
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped

    # NETWORK:
    ports:
      # WebUI Port (9985)
      - 9985:9985

    # ENVIRONMENT:
    environment:
      # Process user ID
      - PUID=1000
      # Process group ID
      - PGID=1000
      # Timezone
      - TZ=Pacific/Auckland

    # VOLUMES:
    volumes:
      # Configuration files
      - ./dev_env/config:/config
