---
version: "2.1"
services:
  tvh_iptv:
    image: josh5/tvh-iptv-config:latest
    container_name: tvh_iptv
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 9981:9981
      - 9982:9982
      - 9985:9985
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - DEBUG=False
      # - RUN_OPTS= #optional
    volumes:
      - ./config:/config
      - ./recordings:/recordings
    restart: unless-stopped
