---
version: "2.1"
services:
  tvh_iptv:
    image: josh5/tvh-iptv:latest
    container_name: tvh_iptv
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      # WebUI Port (9985)
      - 9985:9985
      # TVH WebUI Port (9981)
      - 9981:9981
      # TVH HTSP Port (9982)
      - 9982:9982
    environment:
      # Process user ID
      - PUID=1000
      # Process group ID
      - PGID=1000
      # Timezone
      - TZ=Pacific/Auckland
      # Additional arguments to be passed to Tvheadend (Optional)
      # - RUN_OPTS= #optional
    volumes:
      # Configuration files
      - ./config:/config
      # Recordings Path (/recordings)
      - ./recordings:/recordings
      # TimeShift Path (/timeshift)
      - ./timeshift:/timeshift
    restart: unless-stopped
