---
version: "2.1"
services:
  # -- TVH IPTV CONFIG --
  tvh-iptv-config:
    image: josh5/tvh-iptv-config:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: "NOW"
        VERSION: "UNKNOWN"

    # ENVIRONMENT:
    environment:
      # Skips the DB migrate command execution on container startup
      - SKIP_MIGRATIONS=false
      # Executes a pip install on container startup
      - RUN_PIP_INSTALL=false
      # Enables debug logging
      - ENABLE_DEBUGGING=true
      # Sets Flask Debug mode on. Will restart the process if changes to files are made
      - FLASK_DEBUG=true

    # VOLUMES:
    volumes:
      - ./dev_env/config:/config
      - ./:/app

  # -- TVHEADEND --
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest

    # NETWORK:
    networks:
      - tvh-iptv-config-net
    ports:
      - "9981:9981/tcp" # Webui
      - "9982:9982/tcp" # HTSP

    # ENVIRONMENT:
    environment:
      # Process user ID
      - PUID=1000
      # Process group ID
      - PGID=1000
      # Timezone
      - TZ=Pacific/Auckland
      # Additional arguments to be passed to Tvheadend (Optional)
      # - RUN_OPTS= #optional

    # VOLUMES:
    volumes:
      - ./dev_env/tvheadend:/config
      - ./dev_env/tvh-recordings:/recordings
      - ./dev_env/tvh-timeshift:/timeshift

    ## # DEVICES:
    ## devices:
    ##   - /dev/dri #optional
