---
version: "2.1"

networks:
  tvh-iptv-config-net:

services:
  # -- TVH IPTV CONFIG --
  tvh-iptv-config:
    image: josh5/tvh-iptv-config:latest
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"

    # NETWORK:
    networks:
      - tvh-iptv-config-net
    ports:
      # WebUI Port (9985)
      - 9985:9985
      # Proxy Port (9987)
      - 9987:9987

    # ENVIRONMENT:
    environment:
      # Timezone
      - TZ=Pacific/Auckland
      # The host IP address used to contact this application.
      - APP_HOST_IP=192.168.1.102
      # Application Port (needs to match the exposed port listed above)
      - APP_PORT=9985
      # Enable debugging in TIC application logs
      - ENABLE_DEBUGGING=false

    # VOLUMES:
    volumes:
      # Configuration files
      - ./dev_env/config:/config
