---
networks:
  private-net:

services:
  # -- TVH IPTV CONFIG --
  tic:
    image: josh5/tvh-iptv-config:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: "UNKNOWN"
        BUILD_DATE: "NOW"
        BASE_IMAGE: "python:3.12-bookworm"

    # NETWORK:
    networks:
      - private-net
    ports:
      # App Port (9985)
      - 9985:9985
      # Proxy Port (9987)
      - 9987:9987

    # ENVIRONMENT:
    environment:
      # Process user ID
      - PUID=1000
      # Process group ID
      - PGID=1000
      # Timezone
      - TZ=Pacific/Auckland
      # Skips the DB migrate command execution on container startup
      - SKIP_MIGRATIONS=false
      # Executes a pip install on container startup (might be required to generate the venv)
      - RUN_PIP_INSTALL=false
      # Enables debug logging for main application
      - ENABLE_APP_DEBUGGING=true
      # Enables debug logging for DB queries
      - ENABLE_SQLALCHEMY_DEBUGGING=false

    # VOLUMES:
    volumes:
      # Configuration files
      - ../dev_env/config:/config
      # Application source passthrough
      - ../:/app

    depends_on:
      - tvheadend

  # -- TVHEADEND --
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest

    # NETWORK:
    networks:
      - private-net
    ports:
      - "9981:9981/tcp" # Webui
      - "9982:9982/tcp" # HTSP

    # ENVIRONMENT:
    environment:
      # Process user ID
      - PUID=1000
      # Process group ID
      - PGID=1000
      # Timezone
      - TZ=Pacific/Auckland
      # Additional arguments to be passed to Tvheadend (Optional)
      # - RUN_OPTS= #optional

    # VOLUMES:
    volumes:
      - ../dev_env/tvheadend:/config
      - ../dev_env/tvh-recordings:/recordings
      - ../dev_env/tvh-timeshift:/timeshift

    ## # DEVICES:
    ## devices:
    ##   - /dev/dri #optional
