#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Make folders
mkdir -p \
    /config/.tvh_iptv_config

# Add default configs for TVH-IPTV-Config
if [[ ! -e "/config/.tvh_iptv_config/settings.yml" ]]; then
    cp -rfv "/defaults/tvh-iptv-config/settings.yml" "/config/.tvh_iptv_config/settings.yml"
fi

# Set permissions
echo "Setting permissions"
lsiown -R abc:users /config/.tvh_iptv_config
