"""empty message

Revision ID: 20222080e13e
Revises: e829b6fba2dc
Create Date: 2024-01-22 21:01:59.559757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20222080e13e'
down_revision = 'e829b6fba2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_base64', sa.String(length=500), nullable=True))
        batch_op.drop_index('ix_channels_logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index('ix_channels_logo_url', ['logo_url'], unique=False)
        batch_op.drop_column('logo_base64')

    # ### end Alembic commands ###
