"""empty message

Revision ID: 4d27771deb98
Revises: 20222080e13e
Create Date: 2024-06-07 01:11:11.277594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d27771deb98'
down_revision = '20222080e13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_hls_proxy', sa.Boolean(), nullable=True))

    # Set default value of use_hls_proxy to False for existing records
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.execute('UPDATE playlists SET use_hls_proxy = FALSE WHERE use_hls_proxy IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('use_hls_proxy')

    # ### end Alembic commands ###
