"""empty message

Revision ID: 62e3f7ef0ad2
Revises: 4d27771deb98
Create Date: 2024-06-09 11:56:56.425793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e3f7ef0ad2'
down_revision = '4d27771deb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epg_channel_programmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('series_desc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('icon_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=500), nullable=True))

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('use_hls_proxy',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('use_hls_proxy',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('epg_channel_programmes', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('icon_url')
        batch_op.drop_column('series_desc')
        batch_op.drop_column('sub_title')

    # ### end Alembic commands ###
