"""empty message

Revision ID: e0b4b10647d5
Revises: 46f0f37aab7b
Create Date: 2023-04-29 01:56:56.935675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b4b10647d5'
down_revision = '46f0f37aab7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tvh_uuid', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_channels_tvh_uuid'), ['tvh_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_tvh_uuid'))
        batch_op.drop_column('tvh_uuid')

    # ### end Alembic commands ###
