"""empty message

Revision ID: e829b6fba2dc
Revises: e0b4b10647d5
Create Date: 2023-05-08 09:43:54.479498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e829b6fba2dc'
down_revision = 'e0b4b10647d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epg_channel_programmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_epg_channel_programmes_categories'), ['categories'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epg_channel_programmes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epg_channel_programmes_categories'))
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
