"""empty message

Revision ID: f3d254922d25
Revises: 044b003faaaa
Create Date: 2025-09-02 13:16:18.716341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d254922d25'
down_revision = '044b003faaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epg_channel_programmes', sa.Column('summary', sa.String(length=1000), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('keywords', sa.String(length=1000), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('credits_json', sa.String(length=4000), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('video_colour', sa.String(length=10), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('video_aspect', sa.String(length=32), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('video_quality', sa.String(length=16), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('subtitles_type', sa.String(length=32), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('audio_described', sa.Boolean(), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('previously_shown_date', sa.String(length=32), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('premiere', sa.Boolean(), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('epnum_onscreen', sa.String(length=64), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('epnum_xmltv_ns', sa.String(length=64), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('epnum_dd_progid', sa.String(length=64), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('star_rating', sa.String(length=16), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('production_year', sa.String(length=8), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('rating_system', sa.String(length=32), nullable=True))
    op.add_column('epg_channel_programmes', sa.Column('rating_value', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epg_channel_programmes', 'rating_value')
    op.drop_column('epg_channel_programmes', 'rating_system')
    op.drop_column('epg_channel_programmes', 'production_year')
    op.drop_column('epg_channel_programmes', 'star_rating')
    op.drop_column('epg_channel_programmes', 'epnum_dd_progid')
    op.drop_column('epg_channel_programmes', 'epnum_xmltv_ns')
    op.drop_column('epg_channel_programmes', 'epnum_onscreen')
    op.drop_column('epg_channel_programmes', 'is_new')
    op.drop_column('epg_channel_programmes', 'premiere')
    op.drop_column('epg_channel_programmes', 'previously_shown_date')
    op.drop_column('epg_channel_programmes', 'audio_described')
    op.drop_column('epg_channel_programmes', 'subtitles_type')
    op.drop_column('epg_channel_programmes', 'video_quality')
    op.drop_column('epg_channel_programmes', 'video_aspect')
    op.drop_column('epg_channel_programmes', 'video_colour')
    op.drop_column('epg_channel_programmes', 'credits_json')
    op.drop_column('epg_channel_programmes', 'keywords')
    op.drop_column('epg_channel_programmes', 'summary')
    # ### end Alembic commands ###
