#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Install packages (if requested)
if [ "${RUN_PIP_INSTALL}" == "true" ]; then
    s6-setuidgid abc python3 -m venv --symlinks /app/venv-docker
    s6-setuidgid abc /app/venv-docker/bin/pip install --no-cache-dir -r /app/requirements.txt
fi

# Execute migrations
echo
echo "Running TVH-IPTV-Config DB migrations"
s6-setuidgid abc /app/db-migrate.sh

echo
echo "Starting TVH-IPTV-Config Service"
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9985" \
        s6-setuidgid abc /app/venv-docker/bin/flask run
