---
networks:
  private-net:

services:
  # -- TVH IPTV CONFIG --
  tic:
    image: ghcr.io/josh5/tvh-iptv:latest

    # NETWORK:
    networks:
      - private-net
    ports:
      # App Port (9985)
      - 9985:9985
      # Proxy Port (9987)
      - 9987:9987
      # TVH Webui
      - 9981:9981
      # TVH HTSP
      - 9982:9982

    # ENVIRONMENT:
    environment:
      # Process user ID
      - PUID=1000
      # Process group ID
      - PGID=1000
      # Timezone
      - TZ=Pacific/Auckland
      # Skips the DB migrate command execution on container startup
      - SKIP_MIGRATIONS=false
      # Executes a pip install on container startup (might be required to generate the venv)
      - RUN_PIP_INSTALL=false
      # Enables debug logging for main application
      - ENABLE_APP_DEBUGGING=false
      # Enables debug logging for DB queries
      - ENABLE_SQLALCHEMY_DEBUGGING=false

    # VOLUMES:
    volumes:
      # Configuration files
      - /data/containers/tvh-iptv/tic-config:/config
