name: Build All Packages CI

on:
  push:
    branches: ["dev-**", "pr-**", "staging", "master"]
    tags: ["**"]
  pull_request:
    branches: ["staging", "master"]
  schedule:
    # At 02:30 on Saturday
    - cron: "30 2 * * 6"

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        base-image:
          ["python:3.12-bookworm", "ghcr.io/tvheadend/tvheadend:edge-debian"]

    steps:
      # ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      # ---
      - name: Available platforms
        if: success()
        run: echo ${{ steps.buildx.outputs.platforms }}

      # ---
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo "GITHUB_REF:${GITHUB_REF}"
          echo "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          VERSION_TAG=${GITHUB_REF#refs/*/}
          SHA_SHORT="${GITHUB_SHA::7}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          SERVICE_NAME=tvh-iptv-config
          if [[ "${{ matrix.base-image }}" == *"tvheadend"* ]]; then
            SERVICE_NAME=tvh-iptv
          fi
          DOCKER_HUB_IMAGE=docker.io/josh5/${SERVICE_NAME:?}
          GHCR_IMAGE=ghcr.io/${ORG:?}/${SERVICE_NAME:?}

          DOCKER_TAGS=""
          if [[ ${GITHUB_REF} == refs/heads/master ]]; then
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:latest,${GHCR_IMAGE}:latest,"
          elif [[ ${GITHUB_REF} == refs/heads/staging ]]; then
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:staging,${GHCR_IMAGE}:staging,"
          elif [[ ${GITHUB_REF} == refs/heads/dev-* ]]; then
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:${VERSION_TAG},${GHCR_IMAGE}:${VERSION_TAG},"
          elif [[ ${GITHUB_REF} == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            if [[ ${VERSION} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[-\w]*$ ]]; then
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:${VERSION},${GHCR_IMAGE}:${VERSION},"
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:latest,${GHCR_IMAGE}:latest,"
            fi
          elif [[ ${GITHUB_REF} == refs/pull/* ]]; then
            PR_NUMBER=$(echo ${GITHUB_REF} | cut -d'/' -f3)
            # For PR builds, only tag the GHCR image.
            DOCKER_TAGS="${GHCR_IMAGE}:pr-${PR_NUMBER},"
          fi

          DOCKER_PUSH="true"

          echo "Build: [$(date +"%F %T")] [${GITHUB_REF_NAME}] [${GITHUB_SHA}]" > ./docker/overlay/version.txt
          cat ./docker/overlay/version.txt

          echo "docker_hub_image:${DOCKER_HUB_IMAGE:?}"
          echo "docker_hub_image=${DOCKER_HUB_IMAGE:?}" >> $GITHUB_OUTPUT

          echo "ghcr_image:${GHCR_IMAGE:?}"
          echo "ghcr_image=${GHCR_IMAGE:?}" >> $GITHUB_OUTPUT

          echo "service_name:${SERVICE_NAME:?}"
          echo "service_name=${SERVICE_NAME:?}" >> $GITHUB_OUTPUT

          echo "docker_image:${DOCKER_HUB_IMAGE:?}"
          echo "docker_image=${DOCKER_HUB_IMAGE:?}" >> $GITHUB_OUTPUT

          echo "docker_tags:$(echo ${DOCKER_TAGS} | sed 's/,$//')"
          echo "docker_tags=$(echo ${DOCKER_TAGS} | sed 's/,$//')" >> $GITHUB_OUTPUT

          echo "docker_push:${DOCKER_PUSH:?}"
          echo "docker_push=${DOCKER_PUSH:?}" >> $GITHUB_OUTPUT

          echo "docker_build_date:${BUILD_DATE:?}" 
          echo "docker_build_date=${BUILD_DATE:?}" >> $GITHUB_OUTPUT

      # ---
      - name: Log into GHCR registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---
      - name: Log into Docker Hub registry
        if: success() && (startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---
      - name: Docker meta
        if: success()
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
        with:
          images: |
            ${{ steps.prepare.outputs.docker_image }}
          labels: |
            maintainer=Josh.5
            source.version=${{ steps.set-image.outputs.sha_short }}
            source.project=TVH-IPTV-Config
            source.service=${{ steps.prepare.outputs.service_name }}
            org.opencontainers.image.title=${{ steps.prepare.outputs.service_name }}
            org.opencontainers.image.created=${{ steps.prepare.outputs.docker_build_date }}

      # ---
      - name: Build Frontend Cache
        if: success()
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          context: .
          file: docker/Dockerfile
          target: frontend_build_stage
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64
          pull: "true"
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}
          tags: |
            ${{ steps.prepare.outputs.ghcr_image }}:build-cache-frontend-build-stage
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---
      - name: Build Backend Cache
        if: success()
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          context: .
          file: docker/Dockerfile
          target: backend_build_stage
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64
          pull: "true"
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}
          tags: |
            ${{ steps.prepare.outputs.ghcr_image }}:build-cache-backend-build-stage
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---
      - name: Build Main Image
        if: success()
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64
          pull: "true"
          push: ${{ steps.prepare.outputs.docker_push }}
          tags: |
            ${{ steps.prepare.outputs.docker_tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
