name: Build All Packages CI

on:
  push:
    branches: ['dev-**', 'pr-**', staging, master]
    tags: ['**']
  pull_request:
    branches: [staging, master]
  schedule:
    # At 02:30 on Saturday
    - cron: '30 2 * * 6'

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: ["python:3.12-alpine", "ghcr.io/tvheadend/tvheadend:edge"]

    steps:
      # Fetch shallow git repository
      - name: Checkout
        uses: actions/checkout@v4

      # Use QEMU to build for other arch
      - name: Set up QEMU
        if: success()
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      # Use docker buildx to build the docker image
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: success()
        id: buildx
        with:
          version: latest

      # List available build platforms
      - name: Available platforms
        if: success()
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Generate 'prepare' build arguments to be retrieved later on
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo  "GITHUB_REF:${GITHUB_REF}"
          echo  "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          DOCKER_IMAGE=docker.io/josh5/tvh-iptv-config
          if [[ "${{ matrix.base-image }}" == *"tvheadend"* ]]; then
            DOCKER_IMAGE=docker.io/josh5/tvh-iptv
          fi
          VERSION_TAG=${GITHUB_REF#refs/*/}

          DOCKER_TAGS=""
          if [[ ${VERSION_TAG%/merge} == 'master' ]]; then
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_IMAGE}:latest,"
          elif [[ ${VERSION_TAG%/merge} == 'staging' ]]; then
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_IMAGE}:staging,"
          elif [[ ${VERSION_TAG%/merge} =~ "dev-"* ]]; then
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_IMAGE}:${VERSION_TAG%/merge},"
          fi
          if [[ ${GITHUB_REF} == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            if [[ ${VERSION} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[-\w]*$ ]]; then
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_IMAGE}:${VERSION},"
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_IMAGE}:latest,"
            fi
          fi

          DOCKER_PUSH="true"
          if [[ ${VERSION_TAG%/merge} =~ "pr-"* ]]; then
            DOCKER_PUSH="false"
          fi
          if [[ ${VERSION_TAG%/merge} =~ ^[0-9]+$ ]]; then
            DOCKER_PUSH="false"
          fi

          echo "Build: [$(date +"%F %T")] [${GITHUB_REF_NAME}] [${GITHUB_SHA}]" > ./docker/overlay/version.txt
          cat ./docker/overlay/version.txt

          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "docker_tags=$(echo ${DOCKER_TAGS} | sed 's/,$//')" >> $GITHUB_OUTPUT
          echo "docker_push=${DOCKER_PUSH}" >> $GITHUB_OUTPUT
          echo "docker_build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      # Cache the build
      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Login to Docker Hub
      - name: Login to Docker Hub
        if: success() && (startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Create meta labels
      - name: Docker meta
        if: success()
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.prepare.outputs.docker_image }}
          labels: |
            org.opencontainers.image.created=${{ steps.prepare.outputs.docker_build_date }}

      # Run docker build and push
      - name: Docker Build and Push
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          pull: true
          push: ${{ steps.prepare.outputs.docker_push }}
          tags: |
            ${{ steps.prepare.outputs.docker_tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # Keep only latest cache
      #   https://github.com/docker/build-push-action/issues/252
      #   https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: always()
        run: |
          if [[ -e /tmp/.buildx-cache-new ]]; then
            echo "Cleaning up old cache..."
            rm -rf /tmp/.buildx-cache
            mv -v /tmp/.buildx-cache-new /tmp/.buildx-cache
          fi
