#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u abc)
User GID:    $(id -g abc)
───────────────────────────────────────
"

lsiown abc:abc /app
lsiown abc:abc /config
lsiown abc:abc /defaults
